### ISSUE TITLE
Improve block execution by storing and indexing trie updates by finalized height

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#4309]
## Motivation
Currently, after execution node finish executing a block, it needs to:
1. Store the computation result (updated payloads)
2. Generate the proof for updated payloads

Both the above 2 steps are currently done by the ledger module (mTrie). The problem with that is:
1. Reading payload from the ledger module would have to traverse the trie structure, and since the payload is usually stored quite deep, it creates some overhead.
2. The mTrie is powered by memory, which does scale very well.

## Goal
- The idea is to store the updated payloads in a separate storage (storehouse), such that the register values can be indexed by height and being queried by a single query, which will speed up the block execution.
- A register can only be indexed by a height if this height has been finalized. Since execution node also executes unfinalized blocks, in order to store the updated payloads from them, we will implement a fork-aware in-memory storage.
- For the first milestone, the ledger will be unchanged and still store the payloads in order to support existing checkpoint and state extraction.

## Tasks
- [ ] Implement a fork aware in-memory storage to store trie updates for unfinalized blocks
- [ ] Implement a non-fork aware storage to store and index trie updates by height for finalized blocks
- [ ] Implement a sync module to monitor the block finalization events, and move the trie updates from fork aware storage to non fork aware storage when an executed block gets finalized or a finalized block gets executed.
- [ ] Abstract away the fork awareness by providing a universal interface for storing payload, and internally it will store the trie updates into either fork aware or non fork aware storage depending on whether they are finalized or not.
- [ ] Update the ingestion engine to store trie updates to the storage abstraction
- [ ] Update the block computer to read trie updates from storage abstraction
