### ISSUE TITLE
[State Sync] Add TransactionResults to BlockExecutionData

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4407]
## Problem Definition

Currently, `TransactionResult` is the only type of execution data that's missing from the `BlockExecutionData`. It was originally included, but there was a problem where the error messages from failing tx could be non-deterministic, causing different `ExecutionDataIDs` and thus different `ExecutionResults`. This effectively caused an execution fork given `ExecutionResults` are stored back into each block (even though the actual state commitment was the same).

The specific issue was that the order that the cadence script pre-processor executed checks is non-deterministic (uses map iteration). This means that there is no way to guarantee that all ENs will generate exactly the same error message text for a transaction with a large number of pre-processor errors.

## Proposed Solution

Add `TransactionResults` back into to `BlockExecutionData`, except use the error code instead of the error message text for transaction pre-processing errors. Execution runtime errors can most likely still be included as a string since they are deterministic, but this needs further discussion.

## Definition of Done

* `TransactionResults` are included in `BlockExecutionData`
* The `TransactionResults` schema is updated to use an error code for non-deterministic errors
* There are unit and functional tests covering the corner cases that could produce non-deterministic `BlockExecutionData`
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/4706
- [ ] https://github.com/onflow/flow-go/issues/4707
- [ ] https://github.com/onflow/flow-go/issues/4708
```
