### ISSUE TITLE
[State Sync] Add TxResults and Verification for Execution Data

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4410]
Execution Sync is used to trustlessly distribute execution data among nodes. The `BlockExecutionData` currently is missing `TransactionResult` and is not verified by Verification nodes during block processing.

This epic tracks the work needed to add these 2 features to execution sync.

```[tasklist]
### Tasks
- [x] https://github.com/onflow/flow-go/issues/2120
- [x] https://github.com/onflow/flow-go/issues/2715
- [x] https://github.com/onflow/flow-go/issues/4409
- [ ] https://github.com/onflow/flow-go/issues/4407
- [ ] https://github.com/onflow/flow-go/issues/4408
```
