### ISSUE TITLE
Script Execution on Access Node

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-go#4637]
**Goal**
Implement optional execution of scripts on the access node. 

**Design Proposal**
Script execution is already being done on the execution node by using the script execution engine, which can be reused in this use case. The script execution engine needs to be changed to require slimmer interfaces which will be easier to conform to by the script execution module that will be built and will use the Pebble index database. 
On the database population side, we will create a state indexer module that will be responsible for reacting to new data available from the state sync API triggered by the state requester engine using the callback. The indexer module will use an internal jobqueue to make sure we handle sequential indexing of new block data, as well as have good failover and retry logic already implemented. 
The indexer module will use defined interfaces for persisting data in the indexer database.

A simple overview of the design:
![Screenshot 2023-08-30 at 14 58 14](https://github.com/onflow/flow-go/assets/75445744/5e1bf122-9ad9-4497-8d81-eaf1d5fad212)

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/4667
- [ ] https://github.com/onflow/flow-go/issues/4666
- [ ] https://github.com/onflow/flow-go/issues/4606
- [ ] https://github.com/onflow/flow-go/issues/4639
- [ ] https://github.com/onflow/flow-go/issues/4638
- [ ] https://github.com/onflow/flow-go/issues/4673
- [ ] https://github.com/onflow/flow-go/issues/4674
- [ ] https://github.com/onflow/flow-go/issues/4778
- [ ] https://github.com/onflow/flow-go/issues/4632
- [ ] https://github.com/onflow/flow-go/issues/4640
- [ ] https://github.com/onflow/flow-go/issues/4631
- [ ] https://github.com/onflow/flow-go/issues/4781
- [ ] https://github.com/onflow/flow-go/issues/4806
- [ ] https://github.com/onflow/flow-go/issues/4839
- [ ] https://github.com/onflow/flow-go/issues/5030
- [ ] https://github.com/onflow/flow-go/issues/4776
```

```[tasklist]
### Testing
- [ ] https://github.com/onflow/flow-go/issues/4824
- [ ] https://github.com/onflow/flow-go/issues/4880
- [ ] https://github.com/onflow/flow-go/issues/4881
- [ ] https://github.com/onflow/flow-go/issues/4900
- [ ] https://github.com/onflow/flow-go/issues/4918
- [ ] https://github.com/onflow/flow-go/issues/4919
- [ ] https://github.com/onflow/flow-go/issues/4798
- [ ] https://github.com/onflow/flow-go/issues/4855
- [ ] https://github.com/onflow/flow-go/issues/4928
- [ ] https://github.com/onflow/flow-go/issues/4938
- [ ] https://github.com/onflow/flow-go/issues/4953
```
