### ISSUE TITLE
Storehouse Implementation M1

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#4682]
This is the Epic issue for the storehouse implementation. 

[See storehouse design here](https://www.notion.so/dapperlabs/Storehouse-Design-Whiteboard-2f38e27891fc4e3e91415dbce240f175)

# First milestone: block execution powered by storehouse

## The first milestone will :

- Implement the storehouse and use it to replace the trie for saving and reading the registers.
- Being able to execute blocks without joining the network, allows us to test the changes with mainnet data, reducing the risk of shipping the big feature.
    - This requires updating the follower engine and ingestion engine to fetch blocks and collections without being part of the network

## The first milestone will not:
- Reduce EN memory usage (payloads will remain in memory for easier debugging as we validate correctness of execution when using on-disk payloads)
- Be deployed to mainnet, due to the increase in memory usage
    - In order to reduce the surface of changes, the existing trie logic will not be changed, which means the trie will still contain payloads, therefore memory usage won’t be reduced, but only increase. Since the high memory usage has been a concern to some partners, this feature probably will not be deployed to mainnet, but only a benchmarking environment.
- Enabled by default on master
- Implement data recovery features, such as checkpointing.
    - So that it allows us to start the experiment and iteration with mainnet data earlier
    - This feature will be implemented in the next milestone
- Improve execution speed, because the trie is still producing the old WAL, so we have two WALs (old one and new one)

### Measurement of success:

- Being able to execute mainnet blocks in a private benchmarking environment
- Being able to deploy to one testnet EN. (worst case, we use dynamic bootstrapping to recover the version without storehouse)
- The produced results match with other ENs’
- Being able to catch up on the execution from the root block, and once caught up being able to continue executing latest blocks.
- Being able to restart and continue the block execution
- Being able to handle crash failure by replaying WALs.

## Tasks
```[tasklist]
- [x] Storehouse Interface design 
- [ ] https://github.com/onflow/flow-go/issues/4659
- [x] https://github.com/onflow/flow-go/issues/4660
- [x] Implement OnDiskRegisterStore
- [ ] #4996
- [ ] #4997
```

## Feature branch tasks
Feature branch tasks are not compatible with existing EN's logic, meaning once they are merged, the storehouse will be enabled, and won't support the trie-based EN. If we still want EN to run with trie-based EN, these changes should be on remain on a feature branch

```[tasklist]
- [ ] #4998
- [ ] https://github.com/onflow/flow-go/issues/4677
- [ ] #4999
- [ ] #5000
- [ ] #5001
- [ ] #5002
- [ ] #5003
- [ ] #5004
- [ ] #5005
- [ ] https://github.com/onflow/flow-go/issues/5183
```

## Optional Tasks
- [ ] #5017
