### ISSUE TITLE
[Concurrent Execution] - Remove known bottlenecks

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#4705]
## Problem Definition

Grouping of known bottlenecks and sources of non-reentrancy, which prevent us from running an EN in a concurrent transaction execution mode (EN-CE) alongside ENs running in a sequential transaction execution mode (EN-SE) on Mainnet.

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/4561
- [ ] https://github.com/onflow/flow-go/issues/2736
- [ ] https://github.com/onflow/flow-go/issues/4670
```
