### ISSUE TITLE
[Access] Integrate local execution state indexes into Access API

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4750]
Access nodes can now index execution data into their local databases (https://github.com/onflow/flow-go/issues/4639)

Update the Access API endpoints to use the local data where possible.

```[tasklist]
### Development
- [ ] https://github.com/onflow/flow-go/issues/4754
- [ ] https://github.com/onflow/flow-go/issues/4756
- [ ] https://github.com/onflow/flow-go/issues/4751
- [ ] https://github.com/onflow/flow-go/issues/4852
- [ ] https://github.com/onflow/flow-go/issues/4850
- [ ] https://github.com/onflow/flow-go/issues/4829
- [ ] https://github.com/onflow/flow-go/issues/4753
- [ ] https://github.com/onflow/flow-go/issues/5332
- [ ] https://github.com/onflow/flow-go/issues/4757
```

```[tasklist]
### Testing
```
