### ISSUE TITLE
[Access] Enable Observers to serve Access API using local data

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go#4845]
Once execution data can be synced on the public network, observers can begin to sync and index the data for local use.

Update the Observer node bootstrap to make use of the execution data within their Access API.
```[tasklist]
### Development
- [ ] https://github.com/onflow/flow-go/issues/4848
- [ ] https://github.com/onflow/flow-go/issues/4847
- [ ] https://github.com/onflow/flow-go/issues/4406
```

```[tasklist]
### Testing
- [ ] https://github.com/onflow/flow-go/issues/4849
```
