### ISSUE TITLE
[EVM] Utility command to interact with EVM

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5059]
Create a CLI command to interact with the EVM during testing. 

Implement commands to achieve the following actions on the EVM env:
- [x] Create an account inside the EVM and return the created address as well as store the bridged account resource inside the Flow account
- [x] Query the created account and get the balance
- [x] Deploy a contract to the EVM and get back the address
- [x] Run a function on the deploy contract and get back the result in human readable way

The suggested commands could be named like so:
```
flow evm deploy
flow evm crete-account
flow evm get-account
flow evm run
```

The transaction would be an ethereum transaction which would then correctly get wrapped in the Cadence tx.
```[tasklist]
### Tasks
- [x] Create an account inside EVM
- [x] Query created account
- [x] Deploy a contract in EVM
- [x] Run a function on deployed contract
```
