### ISSUE TITLE
[EPIC] [EFM Recovery - M3] Overview

### ISSUE THREAD

**Issue by AlexHentschel** [onflow/flow-go#5103]
# Broad system-level overview

The following is an overview of which components control the Epoch Fallback Mode [EFM] and which components react to it (all prior to any work on EFM Recovery). Those will probable be the components where the central algorithmic changes will be made.

[👉 Design Document in Notion](https://www.notion.so/flowfoundation/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-e923ca84b4d848c5a17de4b18fb5afd5?pvs=4)

### Components controll EFM mode

The `FollowerState` (mutator) / `ParticipantState`  implements
* [logic for emitting the `EpochEmergencyFallbackTriggered` notification](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L667-L674).
* [sets a corresponding flag in the data base](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L731-L736)

### Components that ingest `EpochEmergencyFallbackTriggered` notification (in-memory)

* [`committees.Consensus`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/consensus/hotstuff/committees/consensus_committee.go#L365-L368)
* [`BlockTimeController`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/consensus/hotstuff/cruisectl/block_time_controller.go#L459-L462)
* [`EpochLookup`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/module/epochs/epoch_lookup.go#L279-L282)
* Metrics: [`ComplianceCollector`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/module/metrics/compliance.go#L228-L230) and the respective interface [`ComplianceMetrics`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/module/metrics.go#L262-L276)
* Pub-sub components for distributing notifications: [`events.Distributor`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/events/distributor.go#L67-L73) and corresponding interface [`protocol.Consumer`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/events.go#L95)

### Components that read `EpochEmergencyFallbackTriggered` flag from data base
* [`InstanceParams` reads the flag from data base](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/params.go#L30-L37) on each call of [`EpochFallbackTriggered()`](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/params.go#L37-L42)
* The protocol `State`  reads the flag from data base when [updating the metrics](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/state.go#L860) during [bootstrapping](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/state.go#L185) or [opening the state](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/state.go#L683)
* The `FollowerState` (mutator) / `ParticipantState`  reads the flag from data base [when finalizing a new block](https://github.com/onflow/flow-go/blob/a7b22f69c97e69d922998fd533ed4edd8064b3f4/state/protocol/badger/mutator.go#L660) 

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/5762
- [ ] https://github.com/onflow/flow-go/issues/5127
- [ ] https://github.com/onflow/flow-go/issues/5723
- [ ] https://github.com/onflow/flow-go/issues/5725
- [ ] https://github.com/onflow/flow-go/issues/5728
- [ ] https://github.com/onflow/flow-go/issues/5631
- [ ] https://github.com/onflow/flow-go/issues/5727
- [ ] https://github.com/onflow/flow-go/issues/5726
- [ ] https://github.com/onflow/flow-go/issues/5724
- [ ] https://github.com/onflow/flow-go/issues/5717
- [ ] https://github.com/onflow/flow-go/issues/6013
```

**Comment by durkmurder** [comment]
Closing as completed
