### ISSUE TITLE
[EVM] RPC server for implemented CLI commands

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5139]
Create a simple RPC server for the implemented commands as part of the issue #5059 

This will expose the commands via standard ethereum rpc spec, which should allow connecting the web3.js to interact with the deployed contract.

That will bring the development experience closer to the reality. 
```[tasklist]
### Tasks
- [x] Implement run rpc method
- [x] Implement RPC server
- [ ] Implement get block RPC method
- [ ] Implement gas price RPC method
```
