### ISSUE TITLE
[EPIC] Flow EVM Core Implementation

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#5241]
This Epic tracks Flow EVM Crescendo Release scope, not including JSON-RPC and Bridge components.

### Must Have
```[tasklist]
### Tech-debt and reported bugs
- [ ] #5149 
- [ ] #5219 
- [ ] #5222 
- [ ] #5224 
- [ ] #4959 
- [ ] #4964 
- [ ] https://github.com/onflow/flow-go/issues/5094
```
```[tasklist]
### COA accounts' new functionalities 
- [ ] #4961 
- [ ] #5179 
- [ ] #5226 
- [ ] #5227 
- [ ] https://github.com/onflow/flow-go/issues/5199
- [ ] https://github.com/onflow/flow-go/issues/5197
```
```[tasklist]
### Cadence Arch
- [ ] #5199
- [ ] #5197 
```
```[tasklist]
### Misc
- [ ] #5099
- [ ] #4967 
```

### Should have
```[tasklist]
### Tech-debt and reported bugs
- [ ] #5198 
- [ ] #5207
- [ ] #4965
```
```[tasklist]
### Should have - COA accounts' new functionalities 
- [ ] #5228 
```

### Nice to have
```[tasklist]
### Tech-debt and reported bugs
- [ ] #5225
```

**Comment by j1010001** [comment]
Issue that also belong under this EPIC but were not linked:
#5268, #4962, #4963, #5129, #5380, #5372, #5441, #5458, #5468, #5514
