### ISSUE TITLE
[Execution] Storehouse Implementation M2

### ISSUE THREAD

**Issue by zhangchiqing** [onflow/flow-go#5270]
# Storehouse M2

As the Storehouse M1 is completed, we start working on the next milestone: Storehouse M2

The goal of Storehouse M2 are:
- Reduce memory usage by moving payloads from the trie
- Improve execution speed from the removal of the old WAL
- Being able to handle recovery from any checkpoint
- Being able to support dynamic bootstrapping

```[tasklist]
### Prerequisite tasks
- [ ] https://github.com/onflow/flow-go/issues/5297
- [ ] https://github.com/onflow/flow-go/issues/5298
- [ ] https://github.com/onflow/flow-go/issues/5118
- [ ] https://github.com/onflow/flow-go/issues/5366
- [ ] https://github.com/onflow/flow-go/issues/5161
- [ ] https://github.com/onflow/flow-go/issues/5217
```

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/5101
- [ ] Implement registerless trie
- [ ] Remove the old disk WAL and checkpoint
- [ ] Implement the new checkpointing and recovery of the trie
- [ ] Implement checkpointing for storehouse
- [ ] Implement state extraction and data migration for storehouse
```
