### ISSUE TITLE
[EPIC] [Dynamic Protocol State | M2]: Key-Value Store

### ISSUE THREAD

**Issue by durkmurder** [onflow/flow-go#5291]
## Context

This epic groups issues related to implementation of key-value store as part of Dynamic Protocol State.

## Milestones

- [x] [M1] Milestone 1: Key-Value Store Implementation Complete
  - KV Store extension to Dynamic Protocol State is implemented.
- [x] [M2] Milestone 2: Minimal Upgrade Mechanism
  - Demonstrate a protocol state KV Store schema upgrade and coordinated restart via service event.
- [ ] [M3] Milestone 3: Deployment & Future

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/5351
- [ ] https://github.com/onflow/flow-go/issues/5326
- [ ] https://github.com/onflow/flow-go/issues/5315
- [ ] https://github.com/onflow/flow-go/issues/5666
```
