### ISSUE TITLE
TPS Load generator fixes

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#5489]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/5745
- [ ] https://github.com/onflow/flow-go/issues/5293
- [ ] https://github.com/onflow/flow-go/issues/5329
- [ ] https://github.com/onflow/flow-go/issues/5492
- [ ] https://github.com/onflow/flow-go/issues/5494
- [ ] https://github.com/onflow/flow-go/issues/5491
- [ ] https://github.com/onflow/flow-go/issues/5490
```
