### ISSUE TITLE
Execution Effort Calibration 2. [ExEC2]

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#5598]
## Problem Definition

See: https://flowfoundation.notion.site/Execution-Effort-Calibration-2-Plan-fa80f35d68334eaca2238002a3b9b8fe?pvs=4
```[tasklist]
### Tasks
- [x] [ExEC2] Use nanosecond resolution for reporting execution time
- [ ] [ExEC2] Change grafana reporting of normalised time per execution effort
- [ ] [ExEC2] Add additional logs to transactions where normalised time per execution effort is far from the mean
- [ ] [ExEC2] Add Recursive least squares method that keeps track of executed transactions
- [ ] [ExEC2] Change synthetic transaction generator, to be able to send transactions to any network
- [ ] [ExEC2] Change synthetic transaction generator, to also allow failed transaction
- [ ] [ExEC2] Add additional transactions to the synthetic transaction generator
- [ ] [ExEC2] Create a database to store transaction execution metrics
- [ ] [ExEC2] Inject a component into the FVM that will upload transaction execution metrics to a database
- [ ] [ExEC2] Collect data from local benchmarks
- [ ] [ExEC2] Collect data from benchnet
- [ ] [ExEC2] Collect testnet data
- [ ] [ExEC2] Data analysis
- [ ] [ExEC2] Write Flip
- [ ] [ExEC2] Collect mainnet data
- [ ] [ExEC2] Finalise data analysis with mainnet data
- [ ] [ExEC2] Update weights
- [ ] [ExEC2] Verify new weights
```

**Comment by j1010001** [comment]
Additional scope for Q4 2025 - increasing the limits with the new weights to accommodate existing transactions that would fail due to lower limits when new metering weights are applied.

**Comment by j1010001** [comment]
Estimation correctness heatmap confirms much higher accumulation of fees around the 0 value, demonstrating improve accuracy of fees calculated (the data is offset because of price adjustment)

<img width="1543" height="812" alt="Image" src="https://github.com/user-attachments/assets/6a44c6e2-45fd-4598-b4f8-114d575689a4" />
