### ISSUE TITLE
[EPIC] [SN Permissionless-5] Resolve tech debt items blocking SN permissionless implementation

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#5686]
This is probably more like an Epic, with a list of smaller - medium sized issues. We still need to compile this list. There are probably multiple security-relevant aspects in the repo https://github.com/dapperlabs/flow-go/issues/ that would become relevant in the presence of byzantine consensus participants and more broadly the consensus node as a whole. 

Probably incomplete list of possibly relevant tickets (each needs to be looked into)

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/4085
- [ ] https://github.com/dapperlabs/flow-go/issues/5562
- [ ] https://github.com/dapperlabs/flow-go/issues/6127
- [ ] https://github.com/dapperlabs/flow-go/issues/5857
- [ ] https://github.com/dapperlabs/flow-go/issues/6087
- [ ] https://github.com/dapperlabs/flow-go/issues/5097
- [ ] https://github.com/dapperlabs/flow-go/issues/5073
- [ ] https://github.com/dapperlabs/flow-go/issues/5010
```
