### ISSUE TITLE
[EFM] EpochExtensionLength Protocol Parameter

### ISSUE THREAD

**Issue by kc1116** [onflow/flow-go#5725]
# Context 
While in EFM, the network remains live because sequences of view ranges for which consensus leaders are defined are periodically added to the current epoch. When should a new view range (encoded as an `EpochExtension`) be added?
The first `EpochExtension` is added to the Protocol State in the same block as EFM is triggered.
To determine when subsequent `EpochExtension`s are added, we introduce a new protocol parameter EpochExtensionLength . 

# Definition Of Done

```[tasklist]
### Tasks
- [x] Implement EpochExtensionLength protocol parameter. (This would be a good application for the [Protocol state key-value storage](https://www.notion.so/dapperlabs/Protocol-state-key-value-storage-497326ff9cf44ff4a70610a0dad329b3?pvs=4))
- [x] Sanity checks WRT finalization safety threshold
- [x] Make it possible to specify the value of this param when bootstrapping to create global value
- [x] Connect `GlobalParams` to be backed by the KVStore
- [ ] (if possible) Move other `GlobalParams` into KVStore as well
```

# Further Reading 
[Design](https://www.notion.so/dapperlabs/Spork-less-Epoch-Fallback-Recovery-Design-II-Epoch-Extensions-a7673e45e9064d12b6b48aa517bd1763?pvs=4#17f64e82bb6746ab91328fff22a7dda7)

**Comment by AlexHentschel** [comment]
For estimating the scope of this issue, we should align on the desired implementation approach. I see 3 options (listed in order of increasing effort):
1. hard-coded parameter (should not be a command-line argument, as inconsistent values would break consensus liveness)
2. The Epoch Setup event could also specify the number of views for possible extensions. This would be a simpler way of making the parameter configurable through governance transactions
3. separate entry in the Protocol State's Key-Value store, with dedicated service event to change it.

**Comment by durkmurder** [comment]
Last PR related to this issue: https://github.com/onflow/flow-go/pull/6272

**Comment by durkmurder** [comment]
PR merged.
