### ISSUE TITLE
[EPIC | M2] Implement epoch state machine in Dynamic Protocol State

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#5762]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/5717
- [ ] https://github.com/onflow/flow-go/issues/5724
- [ ] https://github.com/onflow/flow-go/issues/5726
- [ ] https://github.com/onflow/flow-go/issues/5727
- [ ] https://github.com/onflow/flow-go/issues/5728
- [ ] https://github.com/onflow/flow-go/issues/5631
```
