### ISSUE TITLE
EVM Core Tech debt

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#5912]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/5500
- [ ] https://github.com/onflow/flow-go/issues/5748
- [ ] https://github.com/onflow/flow-go/issues/5744
- [ ] https://github.com/onflow/flow-go/issues/5781
```
