### ISSUE TITLE
[EVM] Backporting EVM to v0.33

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#5954]
Discovery ticket for backporting EVM to v0.33 branch https://github.com/onflow/flow-go/tree/v0.33 

This issue defines the work needed to get the EVM backported to v0.33 to satisfy partners' integration needs. 

Broadly speaking there are 4,653 commits and 1,364 file changes that exist on master but don't exist on the v0.33 branch: https://github.com/onflow/flow-go/compare/v0.33...master 
More specifically for EVM changes there are 103 file changes made on master but don't exist on the v0.33. 

Bellow are general tasks that would be required to backport

```[tasklist]
### Tasks
- [ ] Backport EVM Core contract
- [ ] Backport contract handler using previous Cadence version
- [ ] Backport whole EVM Gateway
- [ ] Create an account for EVM (child of service account) before HCU
- [ ] HCU the EVM and enable it
- [ ] Stage migration for EVM contract
- [ ] Verify Atree Inlining and Cadence 1.0 Support for EVM Storage Account Migration, Including Registers with Non-Empty Owners and Inaccessible Keys
- [ ] Backporting bridge functionality
```
