### ISSUE TITLE
Badger -> Pebble DB - Chunk Data pack Pruner

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#6516]
## Why

**In general, see Epic:** #6515 

**Specifically for this issue:** 

1. Chunks data packs are stored on EN and use the most storage storage (growing ~1TB in 2 weeks, for first 2 weeks of MN26 - traffic dependent). 
2. Pruning requires EN downtime, so requires manual intervention every time the storage gets close to a limit.

## How will we measure success ?

- Validates assumptions that the pruning actually removes chuck data packs from disk.
- No downtime and no intervention is required for maintaining stable storage required for Chunk data packs on ENs.

## Current status

Chunk data packs are already stored in Pebble DB on EN on Miannet. We haven’t implemented pruning yet, current solution requires downtime on EN to remove old data. 
Scope: We have a POC PR based on v0.33, it needs to be ported to master, design and implementation reviewed, required refactoring of the POC PR finished.
No HCU required to deploy, only rolling upgrade.

## Estimate

5 dev/weeks to be ready to deploy.

## DACI

| Role | Assigned |
| ------ | ---------|
| Driver | Technical: @zhangchiqing  , EM: @j1010001|
| Approver | @Kay-Zee |
| Consulted| @AlexHentschel, @franklywatson |
| Informed| Flow protocol Engineering team|

```[tasklist]
### Tasks
- [x] Verify removing chunk data pack and trigger compaction could claim disk space
- [ ] https://github.com/onflow/flow-go/issues/6825
- [x] Add test cases to verify the disk space will be reclaimed after pruned
- [x] generic block iterator
- [x] height based block iterator
- [x] height based pruner
- [x] Extract the chunk data pack pruner into a generic pruner that prune data by view/height
- [x] pruner engine that uses height based pruner
- [x] add pruner engine to execution builder
- [ ] adding metrics and logging to pruner
- [ ] Roll out to Testnet
- [ ] Roll out to Mainnet
- [x] view based block iterator
- [x] view based pruner
- [ ] switch pruner engine to use view based pruner
- [x] Optimize the implementation with pruning by view
- [ ] badger database migration to backfill view block id index
- [ ] migration validator
- [ ] Roll out to Testnet, Mainnet
```

**Comment by zhangchiqing** [comment]
It's been 7 days since the latest spork (Sep 25), and the mainnet EN produces 480GB chunk data packs data.
