### ISSUE TITLE
Performance Deep-dive & improvements

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#6820]
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go/issues/6824
- [ ] https://github.com/onflow/flow-go/issues/6840
- [ ] Profile EN execution to identify improvements
- [ ] Benchmark Atree serialization before implementing https://github.com/onflow/atree/issues/341
- [ ] https://github.com/onflow/atree/issues/341
```
